### ISSUE TITLE
Failing to install dependencies because of  guzzlehttp/guzzle:6.4

### ISSUE THREAD

**Issue by davis67** [Fintecture/fintecture-sdk-php#3]
```
Problem 1
    - fintecture/fintecture-sdk-php[1.2, ..., 1.2.2] require guzzlehttp/guzzle ^6.4 -> found guzzlehttp/guzzle[6.4.0, ..., 6.5.x-dev] but the package is fixed to 7.3.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires fintecture/fintecture-sdk-php ^1.2 -> satisfiable by fintecture/fintecture-sdk-php[1.2, 1.2.1, 1.2.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```
## Reproduce
Install fintecture/fintecture-sdk-php(latest) within the laravel project that uses guzzlehttp/guzzle ^7.0.1

## What I tried
- Installing the sdk with flag  `--ignore-platform-reqs`
- Using optional versions `"guzzlehttp/guzzle": "^6.4||^7.0.1",

**Comment by hugofintecture** [comment]
Hello, we've just released a new version that should fixed your problem because it isn't tied to a specific HTTP client. Could you try it and say us if it works for you? (Just check our new 'Quick install' section in the README).

**Comment by davis67** [comment]
Thanks
